name: Build Docker Image and Deploy Ktor App

on:
  push:
    branches:
      - master  # Trigger on push to master for Docker build
      - main    # Trigger on push to main for Ktor app deployment
  pull_request:
    branches:
      - master
      - main

jobs:
  # Job 1: Build Docker Image and Retrieve Artifact
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 for the Gradle build (Ktor app)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Step 3: Set up Gradle Cache to speed up build (optional)
      - name: Set up Gradle Cache
        uses: gradle/action-build-cache@v2
        with:
          cache-version: 1

      # Step 4: Build the project using Gradle
      - name: Build the project using Gradle
        run: |
          ./gradlew build

      # Step 5: Check if the JAR file exists after the build process
      - name: Check if JAR file exists
        run: |
          echo "Checking if the JAR file exists..."
          if [ -f "build/libs/testcoverage-all.jar" ]; then
            echo "JAR file found: build/libs/testcoverage-all.jar"
          else
            echo "JAR file not found!"
            exit 1
          fi

      # Step 6: Upload the JAR file as an artifact (if exists)
      - name: Upload artifact (JAR file)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: testcoverage-jar
          path: build/libs/testcoverage-all.jar

      # Step 7: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 8: Build the Docker image for Ktor app
      - name: Build Docker image
        run: |
          echo "Building Docker image for Ktor app..."
          docker build -t testcoverage:latest .
          docker images

      # Step 9: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 10: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker tag testcoverage:latest ${{ secrets.DOCKER_HUB_USERNAME }}/testcoverage:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/testcoverage:latest

  # Job 2: Deploy Ktor App (optional step if needed for deployment)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure build job is successful before deployment

    steps:
      # Step 1: Checkout the code again for deployment
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Pull Docker image from Docker Hub
      - name: Pull Docker image from Docker Hub
        run: |
          echo "Pulling Docker image from Docker Hub..."
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/testcoverage:latest

      # Step 3: Deploy Docker container (example: run the container on a cloud service or server)
      - name: Run Docker container (deployment)
        run: |
          echo "Running Docker container for Ktor app..."
          docker run -d -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/testcoverage:latest
