name: Build Docker Image and Retrieve Artifact

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t codingbackend:latest .
          docker images

      - name: Copy JAR artifact
        run: |
          echo "Checking if JAR file exists..."
          mkdir -p $GITHUB_WORKSPACE/artifacts
          ls build/libs  # Check that the build/libs folder contains the JAR
          cp build/libs/testcoverage.jar $GITHUB_WORKSPACE/artifacts/
          ls $GITHUB_WORKSPACE/artifacts  # List the files in the artifact folder

      - name: Upload artifact (JAR file)
        uses: actions/upload-artifact@v3
        with:
          name: testcoverage-jar
          path: $GITHUB_WORKSPACE/artifacts/codingbackend.jar
