name: Build and Verify JAR File

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Gradle Cache
        uses: gradle/action-build-cache@v2
        with:
          cache-version: 1

      - name: Build the project using Gradle
        run: |
          ./gradlew build --no-daemon

      - name: Verify if JAR file exists
        run: |
          echo "Checking if the JAR file exists..."
          if [ -f "build/libs/testcoverage-all.jar" ]; then
            echo "JAR file found: build/libs/testcoverage-all.jar"
          else
            echo "JAR file not found!"
            exit 1
          fi

      - name: Upload JAR as artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: testcoverage-jar
          path: build/libs/testcoverage-all.jar
